name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x]
        database-type: [sqlite3]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start Database
        run: sqlite3 .${{ matrix.database-type }}.db < src/__tests__/data/sqlite.sql

      - name: Run npm install
        run: npm ci

      - name: Build and test
        run: |
          npm run build
          npm run test:db
        env:
          CI: true
          DB: ${{ matrix.database-type }}

      - name: Stop Database
        run: rm .${{ matrix.database-type }}.db