name: Coverage

on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Start Database
        run: sqlite3 .sqlite3.db < .devcontainer/init/sqlite.sql

      - name: Run npm install
        run: npm ci

      - name: Coverage
        run: npm run test:coverage
        env:
          CI: true

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura-coverage.xml
          badge: false
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: console
          thresholds: '75 90'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Stop Database
        run: rm .sqlite3.db
